---
defaults:
    repo_base_url: http://gitlab.infra.svc.k8s.ws.p7-s.net
  repo_base_ssh: ssh://git@gitlab.infra.svc.k8s.ws.p7-s.net:10022
hooks:
- repo: demo/phonebook-frontend
  jenkins_jobs:
  - job: frontend
    jenkins_url: http://jenkins.demo.svc.k8s.ws.p7-s.net
    token: sometoken
- repo: demo/phonebook-backend
  jenkins_jobs:
  - job: backend
    jenkins_url: http://jenkins.demo.svc.k8s.ws.p7-s.net
    token: sometoken
  - job: backend-sonar
    jenkins_url: http://jenkins.demo.svc.k8s.ws.p7-s.net
    token: sometoken
