---
defaults:
  repo_base_url: http://gitlab.infra.svc.cluster.local
  repo_base_ssh: ssh://git@gitlab.infra.svc.cluster.local:10022
hooks:
- repo:  testuser/phonebook-frontend
  jenkins_jobs:
  - job: frontend
    jenkins_url: http://jenkins.testuser.svc.cluster.local
    token: a12fde257cad123929237
- repo:  testuser/phonebook-backend
  jenkins_jobs:
  - job: backend
    jenkins_url: http://jenkins.testuser.svc.cluster.local
    token: a12fde257cad123929237
